module.exports = {
	"logo": require('./menu.png'),			
	"info": require('./info-dark.png'),	
	"back": require('./chevron-left-dark.png'),
	"config": require('./gear-dark.png'),
	"reset": require('./reset.png'),
	
	"blank": require('./blank.png'),
	"dicetable": require('./table4.jpg'),
	"diceroll": require('./dicecup.png'),
	
	"calc": require('./calc.png'),
	"calc-bksp": require('./calc-backspace.png'),
	"calc-add": require('./calc-add.png'),
	"calc-subtract": require('./calc-subtract.png'),
	"calc-multiply": require('./calc-multiply.png'),
	"calc-divide": require('./calc-divide.png'),
	"calc-plus-minus": require('./calc-plus-minus.png'),
	"calc-point": require('./calc-point.png'),
	"calc-equals": require('./calc-equals.png'),
	"calc-clear": require('./calc-clear.png'),
	"calc-att": require('./calc-att.png'),
	"calc-def": require('./calc-def.png'),
	"calc-0": require('./calc-0.png'),
	"calc-1": require('./calc-1.png'),
	"calc-2": require('./calc-2.png'),
	"calc-3": require('./calc-3.png'),
	"calc-4": require('./calc-4.png'),
	"calc-5": require('./calc-5.png'),
	"calc-6": require('./calc-6.png'),
	"calc-7": require('./calc-7.png'),
	"calc-8": require('./calc-8.png'),
	"calc-9": require('./calc-9.png'),
	
	"calc-alt": require('./calc-alt.png'),
	"calc-size": require('./calc-size.png'),
	"calc-loss": require('./calc-loss.png'),
	"calc-strength": require('./calc-strength.png'),

	"calc-third": require('./calc-third.png'),
	"calc-half": require('./calc-half.png'),
	"calc-three-halves": require('./calc-three-halves.png'),
	"calc-twice": require('./calc-twice.png'),

	"minus-6": require('./minus-6.png'),
	"minus-3": require('./minus-3.png'),
	"minus-1": require('./minus-1.png'),
	"plus-1": require('./plus-1.png'),
	"plus-3": require('./plus-3.png'),
	"plus-6": require('./plus-6.png'),

	"support-die-blank": require('./support-die-blank.png'),
	"support-die-air": require('./support-die-air.png'),
	"support-die-armor": require('./support-die-armor.png'),
	"support-die-cas": require('./support-die-cas.png'),
	"support-die-strike": require('./support-die-strike.png'),

	"chevron-left-dark": require('./chevron-left-dark.png'),
	"chevron-right-dark": require('./chevron-right-dark.png'),	
	"chevron-left-light": require('./chevron-left-light.png'),
	"chevron-right-light": require('./chevron-right-light.png'),
	
	"button-plus": require('./button-plus.png'),
	"button-minus": require('./button-minus.png'),

	"add": require('./add.png'),
	"remove": require('./remove.png'),
	"on": require('./abc_btn_radio_to_on_mtrl_015.png'),
	"off": require('./abc_btn_radio_to_on_mtrl_000.png'),
	"unchecked": require('./abc_btn_check_to_on_mtrl_000.png'),//check-checked.png'),
	"checked": require('./abc_btn_check_to_on_mtrl_015.png')//check-unchecked.png')	
};
