module.exports = {
    TOAST: 'TOAST',

    SET_DICE_CONFIG_ENABLED: 'SET_DICE_CONFIG_ENABLED',
    SET_DICE_CONFIG_ZERO: 'SET_DICE_CONFIG_ZERO',
    SET_DICE_CONFIG_DICE: 'SET_DICE_CONFIG_DICE',    

    SET_SPIN_CONFIG_ENABLED: 'SET_SPIN_CONFIG_ENABLED',
    SET_SPIN_CONFIG_NUMBER: 'SET_SPIN_CONFIG_NUMBER',
    SET_SPIN_CONFIG_VALUES: 'SET_SPIN_CONFIG_VALUES',
    SET_SPIN_CONFIG_VALUE: 'SET_SPIN_CONFIG_VALUE',
    SET_SPIN_CONFIG_FOLLOWDICE: 'SET_SPIN_CONFIG_FOLLOWDICE',

    SET_ODDS_CONFIG_ENABLED: 'SET_ODDS_CONFIG_ENABLED',
    SET_ODDS_CONFIG_ROUND: 'SET_ODDS_CONFIG_ROUND',
    SET_ODDS_CONFIG_ROUNDMETHOD: 'SET_ODDS_CONFIG_ROUNDMETHOD',
    SET_ODDS_CONFIG_ATTACK: 'SET_ODDS_CONFIG_ATTACK',
    SET_ODDS_CONFIG_DEFEND: 'SET_ODDS_CONFIG_DEFEND',    
    
    SET_CALC_CONFIG_MODE: 'SET_CALC_CONFIG_MODE',

    SET_BASE6_CONFIG_ENABLED: 'SET_BASE6_CONFIG_ENABLED',
    SET_BASE6_CONFIG_NUMBER: 'SET_BASE6_CONFIG_NUMBER'
};
